 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Akregator", "akregator   -caption Akregator", "/usr/share/icons/hicolor/16x16/apps/akregator.png" },
     {"Avahi SSH服务器浏览器", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC服务器浏览器", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Blogilo", "blogilo  -caption Blogilo", "/usr/share/icons/hicolor/16x16/apps/blogilo.png" },
     {"Cloud Storage Manager", "storageservicemanager", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Contact Theme Editor", "contactthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Empathy", "empathy", "/usr/share/icons/hicolor/16x16/apps/empathy.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome (unstable)", "/usr/bin/google-chrome-unstable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-unstable.png" },
     {"HexChat", "hexchat ", "/usr/share/icons/hicolor/48x48/apps/hexchat.png" },
     {"KGet", "kget -caption KGet  ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KNode", "knode -caption KNode", "/usr/share/icons/hicolor/16x16/apps/knode.png" },
     {"KPPP", "kppp", "/usr/share/icons/hicolor/16x16/apps/kppp.png" },
     {"KRDC", "krdc -caption KRDC "},
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Kopete", "kopete -caption Kopete ", "/usr/share/icons/hicolor/16x16/apps/kopete.png" },
     {"Krfb", "krfb -caption Krfb ", "/usr/share/icons/gnome/16x16/apps/krfb.png" },
     {"NixNote2", "/usr/bin/nixnote2", "///usr/share/nixnote2/images/windowIcon0.png" },
     {"Polari", "polari", "/usr/share/icons/hicolor/16x16/apps/polari.png" },
     {"QQ国际版", "/usr/bin/wine-qqintl", "/usr/share/icons/hicolor/48x48/apps/qqintl.png" },
     {"TM", "/bin/sh \"/home/loonor/.deepinwine/qqintl/drive_c/Program Files/tm/TM\"", "///home/loonor/.deepinwine/qqintl/drive_c/Program Files/tm/TM.jpg" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"Web", "epiphany ", "/usr/share/icons/gnome/16x16/apps/web-browser.png" },
     {"yy", "/bin/sh \"/home/loonor/.deepinwine/qqintl/drive_c/Program Files/yy/yy\"", "///home/loonor/.deepinwine/qqintl/drive_c/Program Files/yy/yy.jpg" },
     {"个人信息管理设置导出器", "pimsettingexporter"},
     {"远程桌面查看器", "vinagre ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-remote-desktop.png" },
 }

 local menudb53804b7d726967c58fcc8c9ca03d27 = {
     {"Cloud Storage Manager", "storageservicemanager", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Contact Theme Editor", "contactthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Evolution", "evolution ", "/usr/share/icons/hicolor/16x16/apps/evolution.png" },
     {"KAddressBook", "kaddressbook ", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KOrganizer", "korganizer ", "/usr/share/icons/hicolor/16x16/apps/korganizer.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"KchmViewer", "kchmviewer ", "/usr/share/pixmaps/kchmviewer.png" },
     {"Kontact", "kontact", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"WPS 文字", "/usr/bin/wps ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wpsmain.png" },
     {"WPS 演示", "/usr/bin/wpp ", "/usr/share/icons/hicolor/48x48/apps/wps-office-wppmain.png" },
     {"WPS 表格", "/usr/bin/et ", "/usr/share/icons/hicolor/48x48/apps/wps-office-etmain.png" },
     {"个人信息管理设置导出器", "pimsettingexporter"},
     {"字典", "gnome-dictionary", "/usr/share/icons/gnome/16x16/apps/accessories-dictionary.png" },
     {"文档查看器", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
 }

 local menue1b7cee794666669f55acead93513971 = {
     {"Feh", "feh ", "///usr/share/feh/images/feh.png" },
     {"GNU 图像处理程序", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gwenview", "gwenview ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"KColorChooser", "kcolorchooser", "/usr/share/icons/hicolor/16x16/apps/kcolorchooser.png" },
     {"KRuler", "kruler", "/usr/share/icons/hicolor/16x16/apps/kruler.png" },
     {"KSnapshot", "ksnapshot -caption KSnapshot", "/usr/share/icons/hicolor/16x16/apps/ksnapshot.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"图像查看器", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"文档查看器", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
 }

 local menu526fe18cc54d217db3fdb0bf6c5e9bc8 = {
     {"Audacious", "audacious ", "/usr/share/icons/hicolor/48x48/apps/audacious.png" },
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Dragon Player", "dragon ", "/usr/share/icons/hicolor/16x16/apps/dragonplayer.png" },
     {"JuK", "juk -caption JuK ", "/usr/share/icons/hicolor/16x16/apps/juk.png" },
     {"KsCD", "kscd -caption KsCD ", "/usr/share/icons/hicolor/16x16/apps/kscd.png" },
     {"OSD Lyrics", "osdlyrics", "/usr/share/icons/hicolor/64x64/apps/osdlyrics.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"SMPlayer - YouTube 浏览器", "smtube", "/usr/share/icons/hicolor/16x16/apps/smtube.png" },
     {"茄子", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"视频", "totem ", "/usr/share/icons/hicolor/16x16/apps/totem.png" },
     {"音乐", "gnome-music", "/usr/share/icons/hicolor/16x16/apps/gnome-music.png" },
 }

 local menu8640cb1581c2ae2de5a1462405b2943b = {
     {"Artikulate", "artikulate -caption Artikulate ", "/usr/share/icons/hicolor/16x16/apps/artikulate.png" },
     {"Avogadro", "avogadro ", "/usr/share/pixmaps/avogadro-icon.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Cantor", "cantor  -caption Cantor", "/usr/share/icons/hicolor/16x16/apps/cantor.png" },
     {"KAlgebra", "kalgebra ", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"KAlgebra 移动", "kalgebramobile ", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"KBruch", "kbruch -caption KBruch ", "/usr/share/icons/hicolor/16x16/apps/kbruch.png" },
     {"KGeography", "kgeography", "/usr/share/icons/hicolor/16x16/apps/kgeography.png" },
     {"KHangMan", "khangman -caption KHangMan ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KLettres", "klettres -caption KLettres ", "/usr/share/icons/hicolor/16x16/apps/klettres.png" },
     {"KStars", "kstars -caption KStars ", "/usr/share/icons/hicolor/16x16/apps/kstars.png" },
     {"KTouch", "ktouch -caption KTouch ", "/usr/share/icons/hicolor/16x16/apps/ktouch.png" },
     {"KTurtle", "kturtle  -caption KTurtle", "/usr/share/icons/hicolor/16x16/apps/kturtle.png" },
     {"KWordQuiz", "kwordquiz -caption KWordQuiz ", "/usr/share/icons/hicolor/16x16/apps/kwordquiz.png" },
     {"Kalzium", "kalzium -caption Kalzium ", "/usr/share/icons/hicolor/16x16/apps/kalzium.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kig", "kig  --qwindowtitle Kig", "/usr/share/icons/hicolor/16x16/apps/kig.png" },
     {"Kiten", "kiten -caption Kiten ", "/usr/share/icons/hicolor/16x16/apps/kiten.png" },
     {"KmPlot", "kmplot ", "/usr/share/icons/hicolor/16x16/apps/kmplot.png" },
     {"Marble", "marble-qt ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-mobile ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-touch ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Pairs", "pairs  -caption Pairs", "/usr/share/icons/hicolor/16x16/apps/pairs.png" },
     {"Pairs 主题编辑器", "pairseditor  -caption Pairs Theme Editor", "/usr/share/icons/hicolor/16x16/apps/pairseditor.png" },
     {"Parley", "parley ", "/usr/share/icons/hicolor/16x16/apps/parley.png" },
     {"Rocs", "rocs  -caption Rocs", "/usr/share/icons/hicolor/16x16/apps/rocs.png" },
     {"Step", "step -caption Step ", "/usr/share/icons/hicolor/16x16/apps/step.png" },
 }

 local menuba08216f13dd1742157412386eee1225 = {
     {"AisleRiot 接龙游戏", "sol", "/usr/share/icons/hicolor/16x16/apps/gnome-aisleriot.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Bovo", "bovo -caption Bovo", "/usr/share/icons/hicolor/16x16/apps/bovo.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Granatier", "granatier", "/usr/share/icons/hicolor/16x16/apps/granatier.png" },
     {"Hitori", "hitori", "/usr/share/icons/hicolor/16x16/apps/hitori.png" },
     {"KAtomic", "katomic -caption KAtomic", "/usr/share/icons/hicolor/16x16/apps/katomic.png" },
     {"KBlackBox", "kblackbox -caption KBlackBox", "/usr/share/icons/hicolor/16x16/apps/kblackbox.png" },
     {"KBlocks", "kblocks -caption KBlocks", "/usr/share/icons/hicolor/16x16/apps/kblocks.png" },
     {"KBounce", "kbounce -caption KBounce", "/usr/share/icons/hicolor/16x16/apps/kbounce.png" },
     {"KBreakOut", "kbreakout -caption KBreakOut", "/usr/share/icons/hicolor/16x16/apps/kbreakout.png" },
     {"KDiamond", "kdiamond -caption KDiamond", "/usr/share/icons/hicolor/16x16/apps/kdiamond.png" },
     {"KFourInLine", "kfourinline", "/usr/share/icons/hicolor/16x16/apps/kfourinline.png" },
     {"KGoldrunner", "kgoldrunner", "/usr/share/icons/hicolor/16x16/apps/kgoldrunner.png" },
     {"KHangMan", "khangman -caption KHangMan ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KJumpingCube", "kjumpingcube -caption KJumpingCube", "/usr/share/icons/hicolor/16x16/apps/kjumpingcube.png" },
     {"KMahjongg", "kmahjongg -caption KMahjongg", "/usr/share/icons/hicolor/16x16/apps/kmahjongg.png" },
     {"KMines", "kmines -caption KMines", "/usr/share/icons/hicolor/16x16/apps/kmines.png" },
     {"KPatience", "kpat -caption KPatience ", "/usr/share/icons/hicolor/16x16/apps/kpat.png" },
     {"KReversi", "kreversi -caption KReversi", "/usr/share/icons/hicolor/16x16/apps/kreversi.png" },
     {"KSnake", "ktron -snake -caption KSnake ", "/usr/share/icons/hicolor/16x16/apps/kdesnake.png" },
     {"KSnakeDuel", "ktron -caption KSnakeDuel ", "/usr/share/icons/hicolor/16x16/apps/ktron.png" },
     {"KSpaceDuel", "kspaceduel -caption KSpaceDuel", "/usr/share/icons/hicolor/16x16/apps/kspaceduel.png" },
     {"KSquares", "ksquares  -caption KSquares", "/usr/share/icons/hicolor/16x16/apps/ksquares.png" },
     {"KSudoku", "ksudoku  -caption KSudoku", "/usr/share/icons/hicolor/16x16/apps/ksudoku.png" },
     {"Kajongg", "kajongg", "/usr/share/icons/hicolor/16x16/apps/kajongg.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kapman", "kapman", "/usr/share/icons/hicolor/16x16/apps/kapman.png" },
     {"Kigo", "kigo  -caption Kigo", "/usr/share/icons/hicolor/16x16/apps/kigo.png" },
     {"Killbots", "killbots -caption Killbots", "/usr/share/icons/hicolor/16x16/apps/killbots.png" },
     {"Kiriki", "kiriki -caption Kiriki", "/usr/share/icons/hicolor/16x16/apps/kiriki.png" },
     {"Klickety", "klickety -caption Klickety", "/usr/share/icons/hicolor/16x16/apps/klickety.png" },
     {"Kolf", "kolf ", "/usr/share/icons/hicolor/16x16/apps/kolf.png" },
     {"Kollision", "kollision", "/usr/share/icons/hicolor/16x16/apps/kollision.png" },
     {"Kolor Lines", "klines -caption Kolor Lines", "/usr/share/icons/hicolor/16x16/apps/klines.png" },
     {"Konquest", "konquest -caption Konquest", "/usr/share/icons/hicolor/16x16/apps/konquest.png" },
     {"KsirK", "ksirk -caption KsirK ", "/usr/share/icons/hicolor/16x16/apps/ksirk.png" },
     {"KsirK 皮肤编辑器", "ksirkskineditor -caption KsirK Skin Editor ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-locale.png" },
     {"Kubrick", "kubrick", "/usr/share/icons/hicolor/16x16/apps/kubrick.png" },
     {"LSkat", "lskat", "/usr/share/icons/hicolor/16x16/apps/lskat.png" },
     {"Naval Battle", "knavalbattle -caption Naval Battle ", "/usr/share/icons/hicolor/16x16/apps/knavalbattle.png" },
     {"Pairs", "pairs  -caption Pairs", "/usr/share/icons/hicolor/16x16/apps/pairs.png" },
     {"Pairs 主题编辑器", "pairseditor  -caption Pairs Theme Editor", "/usr/share/icons/hicolor/16x16/apps/pairseditor.png" },
     {"Palapeli", "palapeli", "/usr/share/icons/hicolor/16x16/apps/palapeli.png" },
     {"SameGame", "klickety --KSameMode -caption SameGame", "/usr/share/icons/hicolor/16x16/apps/ksame.png" },
     {"kNetwalk", "knetwalk -caption KNetWalk", "/usr/share/icons/hicolor/16x16/apps/knetwalk.png" },
     {"picmi", "picmi", "/usr/share/icons/hicolor/16x16/apps/picmi.png" },
     {"俄罗斯方块", "quadrapassel", "/usr/share/icons/hicolor/16x16/apps/quadrapassel.png" },
     {"关灯", "lightsoff"},
     {"华容道", "gnome-klotski", "/usr/share/icons/hicolor/16x16/apps/gnome-klotski.png" },
     {"四子连线", "four-in-a-row", "/usr/share/icons/hicolor/16x16/apps/four-in-a-row.png" },
     {"四邻", "gnome-tetravex", "/usr/share/icons/hicolor/16x16/apps/gnome-tetravex.png" },
     {"国际象棋", "gnome-chess", "/usr/share/icons/hicolor/16x16/apps/gnome-chess.png" },
     {"土豆小子", "ktuberling -caption Potato Guy ", "/usr/share/icons/hicolor/16x16/apps/ktuberling.png" },
     {"对对碰", "gnome-mahjongg", "/usr/share/icons/hicolor/16x16/apps/gnome-mahjongg.png" },
     {"扫雷", "gnome-mines", "/usr/share/icons/hicolor/16x16/apps/gnome-mines.png" },
     {"投弹者", "bomber -caption Bomber", "/usr/share/icons/hicolor/32x32/apps/bomber.png" },
     {"掷骰子", "tali", "/usr/share/icons/hicolor/16x16/apps/tali.png" },
     {"数独", "gnome-sudoku", "/usr/share/icons/hicolor/16x16/apps/gnome-sudoku.png" },
     {"机器人", "gnome-robots", "/usr/share/icons/hicolor/16x16/apps/gnome-robots.png" },
     {"消色块", "swell-foop", "/usr/share/icons/hicolor/16x16/apps/swell-foop.png" },
     {"贪食蛇", "gnome-nibbles", "/usr/share/icons/hicolor/16x16/apps/gnome-nibbles.png" },
     {"连珠消球", "five-or-more", "/usr/share/icons/hicolor/16x16/apps/five-or-more.png" },
     {"连连看", "kshisen -caption Shisen-Sho", "/usr/share/icons/hicolor/16x16/apps/kshisen.png" },
     {"阿莫(AMOR)", "amor", "/usr/share/icons/hicolor/16x16/apps/amor.png" },
     {"黑白棋", "iagno", "/usr/share/icons/hicolor/16x16/apps/iagno.png" },
 }

 local menude71492af019157e5a5ef958b570e760 = {
     {"Avahi Zero浏览器", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Cairo-Dock", "cairo-dock", "/usr/share/pixmaps/cairo-dock.svg" },
     {"Cairo-Dock (Fallback Mode)", "cairo-dock -A", "/usr/share/pixmaps/cairo-dock.svg" },
     {"Dolphin", "dolphin  -caption Dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"Fcitx (使用轻量界面)", "fcitx -u fcitx-light-ui", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KDE 系统卫士", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KDiskFree", "kdf -caption KDiskFree", "/usr/share/icons/hicolor/16x16/apps/kdf.png" },
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption KSystemLog"},
     {"KUser", "xdg_menu_su kuser  -caption KUser", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Krfb", "krfb -caption Krfb ", "/usr/share/icons/gnome/16x16/apps/krfb.png" },
     {"KwikDisk", "kwikdisk -caption KwikDisk", "/usr/share/icons/hicolor/16x16/apps/kwikdisk.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Thunar 文件管理器", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"Xfce 终端", "xfce4-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf 系统配置编辑器", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"打印机管理", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"批量重命名", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"日志", "gnome-logs", "/usr/share/icons/hicolor/16x16/apps/gnome-logs.png" },
     {"磁盘使用情况分析器", "baobab", "/usr/share/icons/hicolor/16x16/apps/baobab.png" },
     {"系统日志", "gnome-system-log", "/usr/share/icons/hicolor/16x16/apps/logview.png" },
     {"系统监视器", "gnome-system-monitor", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"终端", "gnome-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"网络工具", "gnome-nettool", "/usr/share/icons/hicolor/16x16/apps/gnome-nettool.png" },
     {"软件包更新程序", "gpk-update-viewer", "/usr/share/icons/gnome/16x16/apps/system-software-update.png" },
 }

 local menu41282bf95e43c64d579757573a03cdde = {
     {"Accerciser", "/usr/bin/accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Akonadi 控制台", "akonadiconsole", "/usr/share/icons/hicolor/16x16/apps/akonadiconsole.png" },
     {"Android Studio", "\"/home/loonor/tool/android-studio/bin/studio.sh\" ", "///home/loonor/tool/android-studio/bin/androidstudio.svg" },
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"Atom", "/usr/bin/atom ", "/usr/share/pixmaps/atom.png" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Cervisia", "cervisia -caption Cervisia  ", "/usr/share/icons/hicolor/16x16/apps/cervisia.png" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Groovy Console", "groovyConsole", "/usr/share/pixmaps/groovy.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IntelliJ IDEA", "\"/home/loonor/tool/idea-IU-139.225.3/bin/idea.sh\" ", "///home/loonor/tool/idea-IU-139.225.3/bin/idea.png" },
     {"Java Mission Control", "/usr/lib/jvm/java-8-jdk/bin/jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java Monitoring and Management Console", "/usr/lib/jvm/java-8-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java VisualVM", "/usr/lib/jvm/java-8-jdk/bin/jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"KAppTemplate", "kapptemplate", "/usr/share/icons/hicolor/16x16/apps/kapptemplate.png" },
     {"KCachegrind", "kcachegrind -caption KCachegrind ", "/usr/share/icons/hicolor/32x32/apps/kcachegrind.png" },
     {"KImageMapEditor", "kimagemapeditor -caption KImageMapEditor ", "/usr/share/icons/hicolor/16x16/apps/kimagemapeditor.png" },
     {"KLinkStatus", "klinkstatus   -caption KLinkStatus", "/usr/share/icons/hicolor/16x16/apps/klinkstatus.png" },
     {"KUIViewer", "kuiviewer -caption KUIViewer", "/usr/share/icons/hicolor/16x16/apps/kuiviewer.png" },
     {"Kompare", "kompare -caption Kompare -o ", "/usr/share/icons/hicolor/16x16/apps/kompare.png" },
     {"LiteIDE", "liteide", "/usr/share/pixmaps/liteide.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"NetBeans IDE Build 201411290001", "/bin/sh \"/home/loonor/tool/netbeans/bin/netbeans\"", "///home/loonor/tool/netbeans/nb/netbeans.png" },
     {"PhpStorm", "\"/home/loonor/tool/PhpStorm-138.2001.2328/bin/phpstorm.sh\" ", "///home/loonor/tool/PhpStorm-138.2001.2328/bin/webide.png" },
     {"PyCharm", "\"/home/loonor/tool/pycharm-4.0.3/bin/pycharm.sh\" ", "///home/loonor/tool/pycharm-4.0.3/bin/pycharm.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "/usr/bin/qtcreator", "/usr/share/icons/hicolor/16x16/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Sublime Text 3 开发版", "sublime_text_3 ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Sublime Text 3 开发版(输入法修复)", "sublime_text_3_imfix ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Umbrello", "umbrello  -caption Umbrello", "/usr/share/icons/hicolor/16x16/apps/umbrello.png" },
     {"gitg", "gitg --no-wd ", "/usr/share/icons/hicolor/16x16/apps/gitg.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"数据库浏览器", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
 }

 local menu3b6fab8ae1a5e1bef9fa2320d64c4c2a = {
     {"Accerciser", "/usr/bin/accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Jovie", "jovie"},
     {"K 语音精灵", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"K 鼠标工具", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"屏幕阅读器", "orca --replace", "/usr/share/icons/hicolor/16x16/apps/orca.png" },
 }

 local menuc9a6ee90f5d43732e3f6cf4dcaa8493c = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Akonadi 托盘", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Ark", "ark -caption Ark ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Atom", "/usr/bin/atom ", "/usr/share/pixmaps/atom.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"Jovie", "jovie"},
     {"K 语音精灵", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"K 鼠标工具", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KAlarm", "kalarm -caption KAlarm ", "/usr/share/icons/hicolor/16x16/apps/kalarm.png" },
     {"KCalc", "kcalc -caption KCalc", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KCharSelect", "kcharselect -caption KCharSelect", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KFileReplace", "kfilereplace  -caption KFileReplace", "/usr/share/icons/hicolor/22x22/apps/kfilereplace.png" },
     {"KFloppy", "kfloppy -caption KFloppy", "/usr/share/icons/hicolor/16x16/apps/kfloppy.png" },
     {"KGpg", "kgpg ", "/usr/share/icons/hicolor/16x16/apps/kgpg.png" },
     {"KJots", "kjots -caption KJots", "/usr/share/icons/hicolor/16x16/apps/kjots.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMail Import Wizard", "importwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"KNotes", "knotes", "/usr/share/icons/hicolor/16x16/apps/knotes.png" },
     {"KTeaTime", "kteatime", "/usr/share/icons/hicolor/16x16/apps/kteatime.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTimer", "ktimer", "/usr/share/icons/hicolor/16x16/apps/ktimer.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Keyboard", "matchbox-keyboard", "/usr/share/pixmaps/matchbox-keyboard.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Okteta", "okteta ", "/usr/share/icons/hicolor/16x16/apps/okteta.png" },
     {"compton", "compton"},
     {"gedit", "gedit ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"为知笔记", "WizNote", "/usr/share/icons/hicolor/16x16/apps/wiznote.png" },
     {"便笺", "bijiben ", "/usr/share/icons/hicolor/16x16/apps/bijiben.png" },
     {"地图", "gnome-maps", "/usr/share/icons/hicolor/16x16/apps/gnome-maps.png" },
     {"天气", "gapplication launch org.gnome.Weather.Application", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Weather.Application.png" },
     {"字体查看器", "gnome-font-viewer ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"字符映射表", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"密码和密钥", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"屏幕阅读器", "orca --replace", "/usr/share/icons/hicolor/16x16/apps/orca.png" },
     {"归档管理器", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"截图", "gnome-screenshot --interactive", "/usr/share/icons/gnome/16x16/apps/applets-screenshooter.png" },
     {"文件", "nautilus --new-window ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"时钟", "gnome-clocks", "/usr/share/icons/hicolor/16x16/apps/gnome-clocks.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"桌面搜索", "tracker-needle", "/usr/share/icons/gnome/16x16/actions/system-search.png" },
     {"清理器", "sweeper"},
     {"磁盘", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"计算器", "gnome-calculator", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
 }

xdgmenu = function(terminal) return{
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"办公", menudb53804b7d726967c58fcc8c9ca03d27},
    {"图像", menue1b7cee794666669f55acead93513971},
    {"影音", menu526fe18cc54d217db3fdb0bf6c5e9bc8},
    {"教育", menu8640cb1581c2ae2de5a1462405b2943b},
    {"游戏", menuba08216f13dd1742157412386eee1225},
    {"系统工具", menude71492af019157e5a5ef958b570e760},
    {"编程", menu41282bf95e43c64d579757573a03cdde},
    {"辅助功能", menu3b6fab8ae1a5e1bef9fa2320d64c4c2a},
    {"附件", menuc9a6ee90f5d43732e3f6cf4dcaa8493c},
}
end

